name: Server Status Actions
run-name: ${{ github.actor }} is producting out Gitea Actions
on:
  workflow_dispatch:
  push:
    tags:
      - status-*
jobs:
  ServerStatus:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_NAMESPACE: 'pascall'
      APP_NAME: 'serverstatus'
    steps:
      - name: Check out ServerStatus
        uses: actions/checkout@v3
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Build Theme
        run: |
          cd Theme-Light
          npm i 
          npm run build
      - name: Mv theme
        run: |
          mv Theme-Light/dist web/light
          rm -rf Theme-Light
      - name: Login local Dockerhub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build && Push Docker
        uses: docker/build-push-action@v5.2.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.APP_NAME }}:${{ github.run_number }}
